### ISSUE TITLE
Please don't rename repos/releases

### ISSUE THREAD

**Issue by madskjeldgaard** [osxmidi/LinVst3-X#1]
Hi ! First of all, thank you for your hard work with all the linvst bridges. They are fantastic and I love them! 

I am maintaining the packages for your bridges on the AUR. 

Just a heads up - I see you renamed some things in the latest release here. When this is done, it breaks packages and I need to update them so please be careful about this. 

That said: Thanks again for making these. They rock!

best

**Comment by osxmidi** [comment]
> Hi ! First of all, thank you for your hard work with all the linvst bridges. They are fantastic and I love them!
> 
> I am maintaining the packages for your bridges on the AUR.
> 
> Just a heads up - I see you renamed some things in the latest release here. When this is done, it breaks packages and I need to update them so please be careful about this.
> 
> That said: Thanks again for making these. They rock!
> 
> best

I won't do it in the future.

The latest change was because the binaries wouldn't work with Manjaro for some reason so instead of creating a new version I just changed binaries but I won't do it anymore if it breaks things.

**Comment by madskjeldgaard** [comment]
Cool cool. And again, keep up the good work :)
