### ISSUE TITLE
denise dragon fire - can't authorize

### ISSUE THREAD

**Issue by rlb303** [osxmidi/LinVst3-X#2]
Hi, it's my first time using Linvst3-X and i was able to authorize a few of my plugins so far (the Valhalla and BOZ Digital ones) 
But Dragon Fire from Denise Audio gave me an error:  

![Dragon Fire No Auth](https://user-images.githubusercontent.com/40693675/114325339-f5729100-9b05-11eb-9f1e-26ea86bd35b7.png)

I wonder why the plugin can't see the Internet to authenticate? DAW and OS have no connectivity issues. 

I'm running Bitwig 3.3.7 on Linux Mint Mate 20 with kernel 5.11.0-13.1-liquorix-amd64 #1 ZEN SMP PREEMPT liquorix 5.11-27ubuntu1~focal (2021-04-10)

**Comment by osxmidi** [comment]
> Hi, it's my first time using Linvst3-X and i was able to authorize a few of my plugins so far (the Valhalla and BOZ Digital ones)
> But Dragon Fire from Denise Audio gave me an error:
> 
> ![Dragon Fire No Auth](https://user-images.githubusercontent.com/40693675/114325339-f5729100-9b05-11eb-9f1e-26ea86bd35b7.png)
> 
> I wonder why the plugin can't see the Internet to authenticate? DAW and OS have no connectivity issues.
> 
> I'm running Bitwig 3.3.7 on Linux Mint Mate 20 with kernel 5.11.0-13.1-liquorix-amd64 #1 ZEN SMP PREEMPT liquorix 5.11-27ubuntu1~focal (2021-04-10)

I tried it out on Manjaro and Wine 6.6

I didn't get the connection error and I entered some random name and hit redeem license and it then checked and said that license was never issued (obviously).

So it all seems ok.

The connection uses wininet.

The winbind and libntlm0 and gnutls packages might need to be installed for net access (sudo apt-get install winbind sudo apt-get install gnutls-bin sudo apt-get install libntlm0)

-------

The plugin connection output is

2b4e376} could be created for context 0x6
015c:fixme:wininet:InternetSetOptionW Option INTERNET_OPTION_DISABLE_AUTODIAL; STUB
015c:fixme:wininet:InternetSetOptionW INTERNET_OPTION_SEND/RECEIVE_TIMEOUT/DATA_SEND_TIMEOUT 10000
015c:fixme:wininet:InternetSetOptionW INTERNET_OPTION_SEND/RECEIVE_TIMEOUT/DATA_SEND_TIMEOUT 10000
015c:fixme:wininet:InternetSetOptionW Option INTERNET_OPTION_DATA_RECEIVE_TIMEOUT (10000): STUB
015c:fixme:wininet:InternetSetOptionW INTERNET_OPTION_SEND/RECEIVE_TIMEOUT/DATA_SEND_TIMEOUT 10000

**Comment by rlb303** [comment]
> The winbind and libntlm0 and gnutls packages might need to be installed for net access (sudo apt-get install winbind sudo apt-get install gnutls-bin sudo apt-get install libntlm0)

These packages did the trick! Authorized all Denise plugins now. Thank you so much!
