### ISSUE TITLE
PSP InfiniStrip GUI all sluguish and glitchy

### ISSUE THREAD

**Issue by rlb303** [osxmidi/LinVst3-X#3]
Hi osxmidi :) thanks again for those packages in the other issue with Denise Dragon Fire. I got 95% of my windows plugins working with LinVst3-X and that's amazing! (even iLok ones that use cloud/pc authorization, just haven't been able to make Linux see the iLok USB stick yet.)  

This time i installed PSP InfiniStrip VST3 and although the sound processing is working, the GUI is really sluguish! It takes like two seconds for the whole GUI to refresh and update with knob changes. I Googled about it and saw that the dev from yabridge implemented a solution and i wonder if there's a way or workaround to achieve the same thing with LinVst3-X? 

Here's the yahbridge solution: Option: editor_double_embed {true,false} "Compatibility option for plugins that rely on the absolute screen coordinates of the window they're embedded in. Since the Wine window gets embedded inside of a window provided by your DAW, these coordinates won't match up and the plugin would end up drawing in the wrong location without this option. Currently the only known plugins that require this option are PSPaudioware plugins with expandable GUIs, such as E27. Defaults to false." 

I also tried using LinVst-X with the 64 bit VST2 version of InfiniStrip, but the plugin hangs while being scanned by Bitwig, couldn't go further than that. I'm using Wine 6.0 Stable, had some problems with plugins not showing up on Bitwig with Wine 6.6 devel.

**Comment by osxmidi** [comment]
> Hi osxmidi :) thanks again for those packages in the other issue with Denise Dragon Fire. I got 95% of my windows plugins working with LinVst3-X and that's amazing! (even iLok ones that use cloud/pc authorization, just haven't been able to make Linux see the iLok USB stick yet.)
> 
> This time i installed PSP InfiniStrip VST3 and although the sound processing is working, the GUI is really sluguish! It takes like two seconds for the whole GUI to refresh and update with knob changes. I Googled about it and saw that the dev from yabridge implemented a solution and i wonder if there's a way or workaround to achieve the same thing with LinVst3-X?
> 
> Here's the yahbridge solution: Option: editor_double_embed {true,false} "Compatibility option for plugins that rely on the absolute screen coordinates of the window they're embedded in. Since the Wine window gets embedded inside of a window provided by your DAW, these coordinates won't match up and the plugin would end up drawing in the wrong location without this option. Currently the only known plugins that require this option are PSPaudioware plugins with expandable GUIs, such as E27. Defaults to false."
> 
> I also tried using LinVst-X with the 64 bit VST2 version of InfiniStrip, but the plugin hangs while being scanned by Bitwig, couldn't go further than that. I'm using Wine 6.0 Stable, had some problems with plugins not showing up on Bitwig with Wine 6.6 devel.

I tested it out..

The problem I get is d2d1 based.

Start winecfg and then select the libraries tab and then enter d2d1 in the "New override for library" field.

Then hit Add.

Then hit Edit.

Then choose Disable.


The problem with doing this is that the plugin might have visual glitches but unfortunately there is no real solution to that until Wine improves it's d2d1 dll.

**Comment by rlb303** [comment]
Hi again! Sorry for the delay in answering, i've been away for a few days. 

I forgot to mention: i disabled d2d1 when i was setting up Wine. I read it by chance on a forum that people usually disable it. So the behaviour i described happened with d2d1 disabled. I tried enabling it back to see if it would improve the situation but actually made it worse: InfiniStrip hangs when i drop it on a track it doesn't even load LOL. 

So yeah guess there's not much to do on this. Thanks for clarifying the issue though. I sent an e-mail to PSP to ask them about this and what they think about supporting Linux, since iLok cloud/machine works and more devs are jumping into it :) (even the FirComp dev asked me to get back to him on performance/stability on native linux VST3 and it's rock solid!)

Thanks again osxmidi.
